### ISSUE TITLE
Validate architecture passed as argument via -a

### ISSUE THREAD

**Issue by ghost** [bensadiku/genandroidmk_rs#1]
What the title says. It would probably be worth validating whether the value passed is valid for the given apk, to protect against typos and stuff like that. Otherwise you could end up having an error in your makefile and not realize it until your build is done.

**Comment by ghost** [comment]
Note, it may be worth just including every architecture in the makefile, instead of making the user select only one. Then one makefile could be valid for every architecture, you could make builds for different devices without having to change the makefile for each device.

https://android.googlesource.com/platform/external/chromium-webview/+/refs/heads/android10-d4-release/Android.mk

**Comment by bensadiku** [comment]
Awesome feedback! These should be easy implemented. I'm thinking include every architecture by default and only single architecture if `-a <arch>` is passed. If you want to submit a PR, that would be welcome, if not, I'll implement this myself.

**Comment by ghost** [comment]
I don't know Rust, and I'm a bit busy right now. So it would probably be best for you to do it (unless someone else made a PR.)
